### ISSUE TITLE
Make index.html in the path optional

### ISSUE THREAD

**Issue by daroczig** [HenrikBengtsson/R_CRAN_Booster#2]
First of all, thanks a lot for sharing this - very cool :+1: 

One issue I run into is that if you browse packages without explicitly specifying the `index.html`, eg at https://cran.r-project.org/web/packages/logger/, then it does not work as that's required as per regexp in the manifest file.

As I have this structure of URL stuck in my browser ... and whenever I search for a pkg it just auto completes so that I can simply edit the last word of the URL, I never ever add the `index.html` so it's a bit annoying.

Would you be open to removing the explicit need for `index.html` or at least adding some extra items for whitelisting? Happy to create a PR.

**Comment by HenrikBengtsson** [comment]
:)

I added the index thing without much thought y'day simply under the assumption that the CRAN severs would auto-redirect to it, cf. commit db5a1b9.

Yes, please do a PR - supporting more is better.
